hide_agent_reasoning = true
network_access = true
approval_policy = "never"
sandbox_mode = "danger-full-access"
model = "gpt-5.3-codex"
model_reasoning_effort = "xhigh"

[tools]
unified_exec = true
streamable_shell = true

[features]
web_search_request = true

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]
